apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
spec:
  selector:
    matchLabels:
      app: k8s-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: lechuhuuha/k8s-demo:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080