apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: k8s-demo
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: k8s-demo
spec:
  ports:
    - port: 3306 # The ports to expose
  selector:
    app: mysql # Selector used to apply service on all Objects with label app=mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configs
  namespace: k8s-demo
data:
  DATABASE_USERNAME: root
  DATABASE_NAME: test
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: k8s-demo
type:
  Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=
