apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: k8s-demo
spec:
  selector:
    matchLabels:
      app: k8s-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: k8s-demo
          image: lechuhuuha/k8s-demo:2.0
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: database-configs
          env:
          # Use secret in real usage
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: DATABASE_PASSWORD
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Mi"
              cpu: "50m"
            limits:
              memory: "10Mi"
              cpu: "100m"
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080

